# Generated by Django 6.0.5 on 2026-06-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_created_at_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lesson_note',
            field=models.TextField(blank=True),
        ),
    ]
