# Generated by Django 6.0.5 on 2026-07-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_class_type'),
        ('payments', '0008_mark_paid_bookings_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tutor_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('awaiting_student', 'Awaiting student'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('released', 'Released'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='scheduled', max_length=24)),
                ('student_satisfied_at', models.DateTimeField(blank=True, null=True)),
                ('auto_release_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_installments', to='bookings.booking')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.payment')),
            ],
            options={
                'ordering': ['period_start', 'week_number'],
                'unique_together': {('booking', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_by', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor'), ('admin', 'Admin')], max_length=16)),
                ('reason', models.CharField(choices=[('quality', 'Teaching quality'), ('attendance', 'Attendance or lateness'), ('payment', 'Payment or payout'), ('safety', 'Safety concern'), ('other', 'Other')], default='other', max_length=24)),
                ('message', models.TextField()),
                ('evidence_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=24)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='bookings.booking')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='payments.payoutinstallment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
