# Generated by Django 6.0.6 on 2026-07-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_backfill_weekly_payout_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='support_evidence/'),
        ),
    ]
