# Generated by Django 6.0.5 on 2026-07-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_supportticket_evidence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutinstallment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('awaiting_student', 'Awaiting student'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('released', 'Released'), ('refunded', 'Refunded'), ('held_for_student', 'Held for student'), ('cancelled', 'Cancelled')], default='scheduled', max_length=24),
        ),
    ]
