# Generated by Django 6.0.6 on 2026-06-25 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='is_publicly_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='TutorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('government_id', 'Government ID'), ('selfie', 'Selfie'), ('certificate', 'Certificate')], max_length=50)),
                ('document_file', models.FileField(upload_to='tutors/documents/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tutors.tutor')),
            ],
        ),
    ]
