# Generated by Django 6.0.4 on 2026-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_tutor_is_publicly_visible_tutor_qualifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutordocument',
            name='document_file',
        ),
        migrations.AddField(
            model_name='tutordocument',
            name='document_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
