# Generated by Django 6.0.4 on 2026-06-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_remove_tutordocument_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
