# Generated by Django 6.0.6 on 2026-07-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_alter_tutor_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
