# Generated by Django 6.0.6 on 2026-07-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_created_at'),
        ('payments', '0004_alter_payment_booking_remove_review_booking_and_more'),
        ('tutors', '0005_alter_tutor_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='payments.payment'),
        ),
    ]
