# Generated by Django 6.0.6 on 2026-07-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0006_tutor_bookings_tutor_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutordocument',
            name='document_type',
            field=models.CharField(choices=[('government_id', 'Government ID'), ('nin', 'NIN Document'), ('certificate', 'Certificate')], max_length=50),
        ),
    ]
