# Generated by Django 6.0.6 on 2026-07-11 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tutors', '0007_alter_tutordocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tutors', to='accounts.userprofile')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='tutors.tutor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'tutor')},
            },
        ),
    ]
