# Generated by Django 6.0.6 on 2026-07-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0008_savedtutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tutor',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tutor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
