# Generated by Django 6.0.6 on 2026-07-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0009_tutor_account_name_tutor_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='account_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
