# Generated by Django 6.0.6 on 2026-07-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0010_alter_tutor_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=60),
        ),
        migrations.AddField(
            model_name='tutor',
            name='local_government',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='tutor',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
