# Generated by Codex on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0011_tutor_country_tutor_local_government_tutor_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="home_featured_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tutor",
            name="is_home_featured",
            field=models.BooleanField(default=False),
        ),
    ]
