# Generated by Django 6.0.6 on 2026-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0013_tutor_flexible_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='online_class_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='physical_class_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
