# Generated by Django 6.0.5 on 2026-07-22 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0014_tutor_online_class_fee_tutor_physical_class_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='country',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='TutorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price for the entire course', max_digits=10)),
                ('duration_text', models.CharField(help_text='e.g. 3 Months, 4 Weeks', max_length=100)),
                ('schedule', models.CharField(help_text='e.g. Saturdays & Sundays, 4PM - 6PM', max_length=200)),
                ('description', models.TextField(help_text='Full outline of the course')),
                ('rules', models.TextField(blank=True, help_text='Rules for the class')),
                ('requirements', models.TextField(blank=True, help_text='Prerequisites or requirements')),
                ('teaching_mode', models.CharField(choices=[('online', 'Online'), ('home', 'Home'), ('office', 'Office / Studio')], default='online', max_length=20)),
                ('location_details', models.CharField(blank=True, help_text='e.g. Google Meet link or physical address', max_length=255)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutors.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tutors.tutor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
