# Generated by Django 6.0.6 on 2026-07-22 20:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_course'),
        ('tutors', '0015_alter_tutor_country_tutorcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=60),
        ),
        migrations.CreateModel(
            name='CourseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Python Programming for Beginners', max_length=200)),
                ('cover_image', models.URLField(blank=True, default='', help_text='Image URL for course cover')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('3000.00'), help_text='Price charged per class day', max_digits=10)),
                ('days_per_week', models.PositiveSmallIntegerField(default=2, help_text='Number of teaching days per week')),
                ('duration_months', models.PositiveSmallIntegerField(default=1, help_text='Course duration in months')),
                ('currency', models.CharField(choices=[('NGN', '₦ - Nigerian Naira (NGN)'), ('USD', '$ - US Dollar (USD)'), ('GBP', '£ - British Pound (GBP)'), ('EUR', '€ - Euro (EUR)'), ('GHS', '₵ - Ghanaian Cedi (GHS)'), ('KES', 'KSh - Kenyan Shilling (KES)')], default='NGN', max_length=10)),
                ('delivery_mode', models.CharField(choices=[('online', 'Online Class'), ('home', 'Home Lesson (Student Location)'), ('office', 'Tutor Office / Studio')], default='online', max_length=20)),
                ('online_platform', models.CharField(blank=True, choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('other', 'Other Platform')], default='google_meet', max_length=30)),
                ('physical_location', models.TextField(blank=True, default='', help_text='Address details if Home or Office class')),
                ('schedule_days_times', models.CharField(help_text='e.g. Mondays & Wednesdays, 4:00 PM - 6:00 PM', max_length=250)),
                ('description', models.TextField(help_text='Detailed description & course outline')),
                ('rules', models.TextField(blank=True, default='', help_text='Class guidelines and rules for students')),
                ('requirements', models.TextField(blank=True, default='', help_text='Prerequisites & items needed (e.g. Laptop)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offers', to='tutors.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offers', to='tutors.tutor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TutorCourse',
        ),
    ]
