# Generated by Django 6.0.6 on 2026-07-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0016_alter_tutor_country_courseoffer_delete_tutorcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffer',
            name='cover_image_file',
            field=models.ImageField(blank=True, help_text='Upload course cover image', null=True, upload_to='course_covers/'),
        ),
    ]
