# Generated by Django 6.0.6 on 2026-07-24 17:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0017_courseoffer_cover_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffer',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='courseoffer',
            name='days_per_week',
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='category',
            field=models.CharField(blank=True, default='Digital Skills', help_text='e.g. Digital Skills, Academics, Tech', max_length=100),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='hours_per_session',
            field=models.PositiveSmallIntegerField(default=2, help_text='Hours per Session (e.g. 2)'),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='max_students',
            field=models.PositiveSmallIntegerField(default=5, help_text='Maximum Students (1 for Private, 5, 10, 20)'),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('25000.00'), help_text='Monthly Fee (₦)', max_digits=10),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='sessions_per_week',
            field=models.PositiveSmallIntegerField(default=3, help_text='Sessions per Week (e.g. 3)'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='address',
            field=models.TextField(blank=True, help_text='Full address'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='e.g. English, Yoruba, French', max_length=200),
        ),
        migrations.AddField(
            model_name='tutor',
            name='payout_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('wallet', 'Wallet')], default='bank_transfer', max_length=30),
        ),
        migrations.AddField(
            model_name='tutor',
            name='payout_schedule',
            field=models.CharField(choices=[('monthly', 'Monthly (Recommended)'), ('biweekly', 'Bi-weekly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='tutor',
            name='teaching_mode',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseoffer',
            name='currency',
            field=models.CharField(choices=[('NGN', '₦ - Nigerian Naira (NGN)'), ('USD', '$ - US Dollar (USD)'), ('GBP', '£ - British Pound (GBP)'), ('EUR', '€ - Euro (EUR)')], default='NGN', max_length=10),
        ),
        migrations.AlterField(
            model_name='courseoffer',
            name='delivery_mode',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical'), ('both', 'Both (Online & Physical)')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseoffer',
            name='description',
            field=models.TextField(help_text='Detailed description & what students will learn'),
        ),
        migrations.AlterField(
            model_name='courseoffer',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=1, help_text='Course duration in months (1, 2, 3, 6)'),
        ),
        migrations.AlterField(
            model_name='courseoffer',
            name='physical_location',
            field=models.TextField(blank=True, default='', help_text='Address details if Physical class'),
        ),
        migrations.AlterField(
            model_name='courseoffer',
            name='requirements',
            field=models.TextField(blank=True, default='', help_text='Prerequisites & required items'),
        ),
        migrations.AlterField(
            model_name='courseoffer',
            name='rules',
            field=models.TextField(blank=True, default='', help_text='Class guidelines & rules'),
        ),
        migrations.AlterField(
            model_name='courseoffer',
            name='schedule_days_times',
            field=models.CharField(blank=True, default='Mondays & Wednesdays, 4:00 PM - 6:00 PM', help_text='e.g. Mondays & Wednesdays, 4:00 PM - 6:00 PM', max_length=250),
        ),
        migrations.AlterField(
            model_name='courseoffer',
            name='title',
            field=models.CharField(help_text='Subject / Course Title (e.g. Graphics Design, Mathematics)', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
