# Generated by Django 6.0.5 on 2026-07-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0018_remove_courseoffer_daily_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='payout_schedule',
            field=models.CharField(choices=[('monthly', 'Monthly (Last day of every month)')], default='monthly', max_length=20),
        ),
    ]
