# Generated by Django 5.1.15 on 2026-08-20 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_successstory_is_hidden'),
        ('tutors', '0019_alter_tutor_payout_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffer',
            name='syllabus',
            field=models.TextField(blank=True, default='', help_text='Dynamic week-by-week course syllabus breakdown set by tutor'),
        ),
        migrations.CreateModel(
            name='IntroCallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='Phone or WhatsApp number for discovery call', max_length=50)),
                ('preferred_call_time', models.CharField(help_text='e.g. Tomorrow 4:00 PM, Weekday evening', max_length=100)),
                ('notes', models.TextField(blank=True, default='', help_text='What student/parent wants to discuss')),
                ('meeting_link', models.CharField(blank=True, default='', help_text='Google Meet link, WhatsApp link, or phone number set by tutor', max_length=255)),
                ('meeting_method', models.CharField(choices=[('whatsapp', 'WhatsApp Call'), ('google_meet', 'Google Meet'), ('phone', 'Direct Phone Call'), ('zoom', 'Zoom Meeting')], default='whatsapp', max_length=30)),
                ('tutor_reply_notes', models.TextField(blank=True, default='', help_text='Instructions or note from tutor')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted / Link Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_call_requests', to='tutors.courseoffer')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_call_requests', to='tutors.tutor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_intro_calls', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
