# Generated by Django 6.0.6 on 2026-07-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_alter_chatsession_options_chatsession_last_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='last_message',
        ),
    ]
