# Generated by Django 6.0.5 on 2026-07-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageStatsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_tutors_offset', models.IntegerField(default=678, help_text='Starting count for Verified Tutors')),
                ('lessons_completed_offset', models.IntegerField(default=5000, help_text='Starting count for Lessons Completed')),
                ('cities_covered_offset', models.IntegerField(default=793, help_text='Starting count for Cities Covered')),
            ],
            options={
                'verbose_name': 'Homepage Stats Setting',
                'verbose_name_plural': 'Homepage Stats Settings',
            },
        ),
    ]
