# Generated by Django 6.0.5 on 2026-07-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_homepagestatssetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagestatssetting',
            name='parents_joined_offset',
            field=models.IntegerField(default=1500, help_text='Starting count for Parents Joined'),
        ),
    ]
