# Generated by Django 6.0.5 on 2026-07-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_account_details_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_account_details_update',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_update_effective_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
