# Generated by Django 6.0.5 on 2026-08-01 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_last_account_details_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Rating out of 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
