# Generated by Django 6.0.5 on 2026-08-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_successstory_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagestatssetting',
            name='video_section_active',
            field=models.BooleanField(default=True, help_text='Toggle to show or hide the video section on the homepage'),
        ),
        migrations.AddField(
            model_name='homepagestatssetting',
            name='video_section_subtitle',
            field=models.TextField(default='Watch our short overview to see how our AI matching, verified background-checked tutors, and safe lesson delivery empower learning across Nigeria.', help_text='Subtitle description for the video section'),
        ),
        migrations.AddField(
            model_name='homepagestatssetting',
            name='video_section_title',
            field=models.CharField(default='Discover How MyteacherConnect Works', help_text='Title for the homepage video section', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagestatssetting',
            name='youtube_video_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/watch?v=dQw4w9WgXcQ', help_text='YouTube video URL (e.g. https://www.youtube.com/watch?v=VIDEO_ID)'),
        ),
    ]
