# Generated by Django 6.0.6 on 2026-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_duration_and_rate_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='class_type',
            field=models.CharField(choices=[('online', 'Online Class'), ('physical', 'Physical Class')], default='online', max_length=20),
        ),
    ]
