# Generated by Django 6.0.5 on 2026-07-22 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_class_type'),
        ('tutors', '0015_alter_tutor_country_tutorcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tutors.tutorcourse'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='class_type',
            field=models.CharField(blank=True, choices=[('online', 'Online Class'), ('physical', 'Physical Class')], default='online', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('days', 'Day(s)'), ('weeks', 'Week(s)'), ('months', 'Month(s)')], default='weeks', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_value',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rate_period',
            field=models.CharField(blank=True, default='weekly', max_length=20, null=True),
        ),
    ]
