# Generated by Django 6.0.6 on 2026-07-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_course_alter_booking_class_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='course',
        ),
    ]
