# Generated by Django 6.0.6 on 2026-07-22 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_course'),
        ('tutors', '0016_alter_tutor_country_courseoffer_delete_tutorcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='course_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='tutors.courseoffer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='weeks_completed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='weeks_total',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='class_type',
            field=models.CharField(choices=[('online', 'Online Class'), ('physical', 'Physical Class')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Day(s)'), ('weeks', 'Week(s)'), ('months', 'Month(s)')], default='weeks', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='lesson_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rate_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rate_period',
            field=models.CharField(default='weekly', max_length=20),
        ),
    ]
