# Generated by Django 5.1.15 on 2026-08-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_course_offer_booking_weeks_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='class_type',
            field=models.CharField(choices=[('online', 'Online Class'), ('physical', 'Physical Class'), ('both', 'Both (Online & Physical)')], default='online', max_length=20),
        ),
    ]
